# Generated by Django 5.1.1 on 2024-10-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100)),
                ('recipe_description', models.TextField()),
                ('recipe_category', models.CharField(choices=[('appetizer', 'Appetizer'), ('main_category', 'Main Category'), ('Desserts', 'Desserts')], max_length=20)),
            ],
        ),
    ]
