# Generated by Django 5.1.1 on 2024-10-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0003_recipe_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_category',
            field=models.CharField(choices=[('Appetizer', 'Appetizer'), ('Main course', 'Main Course'), ('Dessert', 'Dessert')], max_length=20),
        ),
    ]
